apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infra/rook-ceph
    repoURL: https://github.com/drewjprosser/argo-storage.git
    targetRevision: HEAD
    directory: 
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true