---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA1u82bUhUk2Z6adW7z20Ok7dV9AoU/slRZK1onO8GcQ4lGE8+7Vpj77vYWovXgn9rZcrTqtMRDDsi0ULXsDCECSoOqwtKXpOdOdJFVtuayIs2m6HW+JaEkUMRqAV67Y4eFFhLHOH6sbqjlFid5+sUlNX001JZlmoIx+pUMOWOYwiySzjtuZOxRRM3PlOz8ZBiDnYrpBqVWKDQKrmOOyyvi6neI0Gg7J6nPrpexv0HZFo8HZ5kqlDtTRx9t56eLr0tnBP2uL7/fIaNs9VU1LUA00fPOlOUkHN/iTgOb46insoyFPVfsD0S+08xDwpicIkHcpKytW9Gz5UgzvMF6vMu/QCVf50Vzxi9NvAjRvTxRyhwyH1SBMSrdcV4b1bUI5HlSl3koZd7AVcKaX99xuKpQmeqHB60rxEXaQEwth3FbgrEvThIq8TC3GHJHxRqi1S97qTBjDp67yvxZb98qKvutK31JEPpqigiYMkBBCxoYtiHcqMvdscTBP0A86lXMlki3ykt7VtfTeYTn84YV9bhycdc8a/cV8n+hzq8NNhb4pL2Zfk0o3S2SWEFCE6QqeXEXMexQlvDdARV4xQixhAlUQe8dkepDp+er5bCTp5JDPC8qvY0da30SEbyUP3xNBRmc9FAyHQQ2queeBYAQYkyLEzVKQpdb4qRmUPMKt/+Ca1U1ZPfxrZP9GbFhIjEpF2dD++G03yr9HBW0/les/Z8g5bgIR8fq6OHu7PMrtAf8QwhVQlFSOlG1
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
