---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBG5ULuYC+GuYHeqaKf9CfiK2HnLf9wyfR4Fe8Qre8ddqv6Ll6JvsFSeTpc2K67CNOM+LoMenDCsZo4v2YoL0f+Uag/EgxmWezI+eWvkvktlEG88ixEYKGpndrBIP7HFXSMyC0fDnhzQMA1Bq3pmyZwP9hyuTsy2BdkRRz2AdZb31i3YTg+lDN9FHaoTUIJlxpTyjHeHs7U4H26wVA2RRG5g8nD6y0yifAdlLrP0extNCBjFoHokPbiYqVuRXQhyhQq03I+qACxPWLgWb46NY+g93h36EHH5aN77U/t1C2FgkOA61k0kNjU/zA0YAm8eo+SUS07X3FZUE9RQHbgrTUYzanQge7gP0LGe2soDOg2+8kJtPGLpiqZUXzAGErgjWXlRmUJnJWX1iGJM/s3nOWPJG6hbTqzS6xzoRvIl+CLx75CIwClLPcuZz7NMS9o1lBp04m0LTawy+1iK2bRFo9x4UjXReGAwONU9vy5wzBQKkSp2UGQR6lfizl/qudZEYtJAq3/HpoXr6KqzSFmqFo7pwAr+/UeaGhBK5H/I6mkOI12Kn8zobCAZ1WNzt77h5qNUSQcgUL5cAPB5Ngw4VQWzHdAe6a6K7jFBQ+3X3tSCuh+7d07PDWItK6E5jkFLHdhpWYawValR6HURnZPH33hKp3qO4GM/FP0GSjl0Xa9/CWvVcBoRpglhStDJnk4EMGv9gsRjM/ppNf8GdNG0DPv4Yda43MrwOaCfxoAeUV9Pjcxc5/w/rr6
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
