---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC1GPg9oUxSHXjwIRhdPnrhbZqn2X692Uvgh47dviyUKWU6PsT2Y5Ds7AK8tuaB2gasLug8t/VoMFaVvobskH5USQRRehFf9kAxsDjM7zjhIzod/0y+ZrziaKP3ndLYncMoVVOw8dZG+iLbafNhiWsK0xK3P5ZKG7gYYFaowrBZTAykNN7WnFmsO+zWpi/xd8RRMwthMQErgVYYVnnMmfaDCkztPvDij8XGiJdBzcpVQKe8+Xrb90n7DJP1usD5jXlJsFREWCudrXwdMm2W8KeGoS0C7K3JEkja/infLIJiB1YqWtUcmserYnltEFeP8aVtB2X7dh9ayjkwvsGQwZFXjSW/pYcevyz3XYlCqFDDCYiMQbP90HkJoqr3YgkeIykURkNbdW4RbmRehtlH9VmQhBZACWKk+07Fi3Lr2uz82yxQA1+PBn+Z+rqZdj1K74OQHxlyO11WEMDWoQ7+tjgmvHn2BcLsTojLS/ER6rZCBABbrjI9BAfA6RsJ0PLe5X9uHdxvAnoQuCmS7axB/QESd3wwgGSWWoIcjb6cn17011zoa23IcaEskM8E2LNlLQzDnqTAYprdOWmJxWbBYZTUfoARs2kMcSWisCZoRerT+cisepsQike2cn0pDYVp8SErd04wcft7ETW7jri0JqYEkSBFKqRfQ6Tc0dHujBmSuXk9P+hNYqFG+Xx70DcHQk3vczr57+0bYeoNf55UlZ923X4PLG4hy2Q/++inOhTg91KYI9iY1UEP
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
