---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB+bsQ3xXowtWbSs0jlCfL0Rpen33jxnB8htSy0yNk74xHAJ3D2A+bH3grlLu0lBThWd9CbJrvDdVj7DH/hmLZIwGXzF8yLLr9CBAz++od5mhTtKxFrjiNGydDkQkz0mtZkvlfUGhU2JbgaTF3tC/Ol4H3MbaEU8BufgnkJE/mUhwSFbNzld2VsvnQdburGCm/WTjdymIPGJFiFFLEzEsKDPYx9CJpVoCDkyJSa0G/GUqh1b733ySkG3zeQgK+zmnoyCxyMI3uqU+6r7SD7sVDgEB6IzE2YwmHcURERtObP2cyDdY3cMtgVIEwZkGD0GsBOmriobjttAGSka43Yt179XEAfO1T3v1p4fkO2vV10684pwZPwLRdzipcjoMYQHj0trhqO1VfhqgS7cmWB216qfskUmULtPIPjAbxwgf+g+xg0iJ+Fqc2HRJJKUvgxyrH7O8+W8MUizjWxxrF/kjhC8Jjzm6WXtQhKt1RxoqXr+yQnftdLXRXY6iHQJc1a70+vfiHuhr6kV68YY9Ro/Ab9oIuDgrJuR134uJ23eFQptlGnP3ITkSsn7gtY5ZNHo+8fpI7W7YoO2sfiC1pdnIAht9w2GPEf0nofTn80iw+Bk/6tDEoxZDTtfm/PpKcEofkMwQIUz6DYX4PxMv343lOukOF0fPHABfaqoe7z/JlWjheTnTVHJGs80UYtAxV+alds/uq5S5LDqHqt2HAOpBBk8Pw326knpPNnNJPpD1OpDsrwn5rK+0GD
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
