---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgATeNIWA80uhaJVWqQY7Chd0kqTeG9GJMfCRVdQui/dzFm3X1+4dd6JXrkAWwWeHvPFt44fvs1r/HphhpUlpV0oXq0u/ZqH1e8cn7frHr4CUQSEkX2GbLxKNUMgbinoVm79cPGdMHxRnN4ZM+I6X3PSoczxU7RAfsFwVxGZkJhwrzejbPdpYbB7iv8AwSewmBvWAtHdgJwAkTXNEBgmSwAoIW2KZG42nFJxTHUSm8Xf+p8r+V42EB4CbZmixLsTW3hU7dCoIJa73YTFz+yIR+AYranybSce4cSnc1jRMPDT+J1l2xFRO5ctn0eseuOoB0zB7i7MrsKEGc8+ILBAvAtjfF4gkEYXGkIQILxSWwrOYJ2DRhl5nKlDwEsVNf5Cz7xgClxPI9nsTkKtaFOqFAjxxpVi8GUOS0sgteodJ9XV0LwVKQPe0s+fw0Yq+uxtom2+3T+KSGfY6wTpFfBQrVwG9oEDXlPESWhXDh0Un7k2tmUu8GHCOEaffCzIzpviSdhtl/cs2ROOYP0NJy4XzQcX3rbqowOkxw52gM6S6CDtCCDP7FLuVECzW0QekAHTsk8QlUFjiEwEHt3CJi2QLxQZ1bH4z/6InxM+Wxklg3ghXYagdDCzluksbgV9A0SZDqki5N1r3E+OIRc23uuHcd/J0gDyUgxm3gq8plAZ0nLpYTSLCCPaUPOPDewWJxoxQlgdQqORW0fuF4jkjEk1EDIIomg3g5XKAqme+slb3gzUGp713qOXSnCS
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
