---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCgVU51wpQAmd2pnhCQCUafyt1QBaYma2UTTebeLDdlUeN6DcavFyxm8aQGZKD4f+FZ2Dk775f505EY0NE9bjzNOWc9b8Fk1i81i76VeCm3lfmrlwDhHHCuoui2ZFEIn5hqZTIB6gCFDyV4/30HaLO+QpiYJ+FO+Cv0Sxulse/E/FDqmMiGNoPDuUrmq3Ul/mJfvChoSZbzlFrG6cf4MFhjwYvr8Xo/8gYbU7i7pm+8pErNyyorpVnOFTG9SRfjmN1+pitpDdg1WBtL6fqpuUBL9vf4pcUgnMSDzraZxVxeekfVuxMiWcT2T3x8UJKsDgcXSBLbWnOJycYiCDdC4wvbKRdX03H3kY3O7e48p58harwU3nluPXN2jxxCvkWAA32y44w6uui9Znyt1Vtp7g/Nz4FooO0VmSE2TxnS3f4a15myFq08YcozX5q0cR7YihHDMSadeXa9ser98pnSKIX3Runstp3OCqYdIjn/euFHjS0DAW5V6Wk/BN/bDM3o6z7z3KHw/UDGhoxNwXwvak/FF//oLwfBOe3u38Ae+rWL819LjJWy8VouXwgwphICCY3Z3DhAEECATPPrZjv2Xbi5vfUn3SccOBoLAXLLBLCasa8g+GCJKQVLzw2pyNVRF5riYGc336zfIOmGfKg+OU9CPVga8NLws2P7USioHbpl/T9/c29DlBBN4kXD/wo3ElStOoTdqShK1n9NwrvCg0g5SV/iM1J6yHULn5qjJERNFVjN+CI9PoUG
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
