---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB7idP4Ztjf+jzkZD588dzqJi5xF5new2KJE/yKtiC3dhGoe40bycdG6WWFXqYmAmQ5K9puSTXBOZp8k0Ps+PKRDa4ntjfAboh/3/5ADyBbNYG6bEeWdqWyFrBd/guLNpg/26MmLXSRckdyi9qk9cPqR/KgYxR+MNPNxKUH+5fH53hjYDNfrz4DaELWZuPvyrEHAMgs6ocmIvD+dtrp9fn0s8mlxP1jJyh6yGnliF3A9j0gKCMcLy5eqOTV6Y3TSubCag6kdiuHEx3UjxE/a//VjkSBiNJoIVZ5WRyn8V+mk8fMkSKqKPmKvnJap8URbN+zi2E/dgP6VZm7/LlSuBas9AZTjrbq88/Ivz+12Id2ADugrevaO4Nct5N53ZmjHZLMSjuBrRfNpyHvRR9wkean/zMN1BWxKYFac61ypDHpEj2lQg3S7v3PYBAu2dWnxcGBdT50gfKKgJP/o4VEl6M7J/GXUH+E5fTbS/mEpWB0QhV0dSfFBUaetGdTIeMBGDATF5xlbMkBfA22id/85VtrH0nzIkXEUztgiCU3RmhDyGk32owQ/GzogPZrbRfSQ8iFjCQkNA78yALQnxkgzHgjkoWFQSs3ktsUB4jiU1AA8QH7rnF2/BQEgf8IlLFVEKfcOGQN+4SEAKTC4l0hipmYXV8OD4ILy+DH+GHR9iOS0B7ntSXDi3PSO+kTDrkLg26yVQ4EE2IEAFDLaxCrgWJtOnmBWvoL4u1Ze0jhxIxk8TKFuCylvm2l
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
