---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: storage-user
  namespace: minio
spec:
  encryptedData:
    CONSOLE_ACCESS_KEY: AgDJZoPhn2tr6gQAhefQKfxVn2XN4iGN0wdftcyqi0t5e736uA/4XIDPv1f9Zu4CqSQIoPNfcFkMZJh7ZsgDeykoj0jWCMVhxtqpSXkE4+SIT5YzZFlCa44KZzhEBvryzu8wqS74UtKNjSDanWpG4CYNA31rBCMVXPuOD6aSttTTWY/ZaKk7HSiljMWFFGjlAt3psw7eygZfDxnT22lu1aoCBd7dVSzEZDEJ7QjUuPBAKNoq1VB2rc01VW+EMxvlt0iba5l7YTE06fM6d9nPmlu3fc3PJz7aKDIteRy52aEMtHdh8RWvF2EJn61A+Jci5zKplbwZD5vr2hl5Tvb2YQvAu13XpmtV3d51e7XxaZbQ2R6JDGQ0y0M/6NfWuzOJu85KqPs73W3xqv2SYIu+FP3MVAA4MZe1P8ucnNx5EoAeorP2y/n3O4GZLhoIIdOHAZ0K2Fk4H773jeYsO60+cVuPt4Nh1MLq13Ac18EOquzO9/9KQmKUfA2Jse3n/fy0dks0IBb26p07KiUXTQBoWxs5VURXDN7qoHRGe7kaaVoT4uMKRSuERHSZWyB2h4V0WkN1H9BHCCOHcHXljUaDxi77StGoDhyfcOveAmXMhntZry4APBlQXda2e+f3K2kPhRvGt6Ty6JgYiY+5B9ckE9+3N66TXY7VokpEQv2Ba/5VMklpX3ijj4R3x3hk8Ks95gGc8iz0dzU5
    CONSOLE_SECRET_KEY: AgC7A0aKOIS5AhKCdi8fpCFAi+RpKi5ncuNMBRDdqFIOZKSywnKOVqtQbcM9ck/Aw+C5Wzw7+L8qqGq/v3SAU70ITid33Hhpt3MDN/RwIbPKL9DsbXuVBWeDzeXIy6+WOz/GPomxIW9szIMsXoL5h5qVPdS+nlpu0JXbC250+z16L7PdwUCgDMack+jUwbKtr8tnaGwLfGSQLc0YY0EeaG9/TgNojJ3VhqlhtorswTJSiX87v8hMURgWDvvzMnfCFWtdFlUDc8NYG5iCiPV+idF+FhK1XxubLLalWxBWPzGay2WknRmW9thWdaBk8mRAKo2BIPi5Bgn9v2hBU2X/nLk8XhG+WE6FRhD7/JdXkEfuX7+U/lakq9mKyN7OuBPA+msmRgPaPFqyRbDy78FFiZvp3t4+VqS9/U6erhHzfw4s2Mx7PKyScNQvwtICrRHhkgVFonsjcqVOhuW5rkNXGSN2dg+3Y8sFe6BbR3vm2HXZIrzZ+1A/kABC0gaO1yRXk8v8GRTivOYCf8pGcqw87RLFChwhbmwIpjuIT4IyjG9C3GwnMZI8AI9cmuQyidz4RgFl49emMTF5ZK8Bwk0GLDxqk1JlDrhfpyWCh90EpNFnpH+gmyXzuMgwdoQgB4Mki7A/WDlk+14rZAtagmV45+souc3+u6ik9ZJzUVIuYrRU7ZHxsGDQksPGh1IMb7f8A0J3wsXvahgyZv0K
  template:
    metadata:
      creationTimestamp: null
      name: storage-user
      namespace: minio
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: storage-configuration
  namespace: minio
spec:
  encryptedData:
    config.env: AgC8pGI0rZwSx4sCauy+vpqHwo1Llr+W64u0nwnwtQrlwWL453GPKVHZSKFF59cv1u7WUENpM1jPKogJFH5nFah3/BFglMX8SENYYd42RZ/dBdS/qA4KJE8cB+gyaMwNy/KTpJUtecDgGheGEmVmp67F1rEFQ6M+cbekO7KIJsST0GR8a99iyAr3rxpYDRerm0cC2k0uv0sxiAYCOf1p1C9mtRQX1ZIN4VGQXfkSIiCUc7imyWfmDZihnZdIK9WKJNbwUwGSR38kxLQAZgxUOjhQUBnjU9/H4cYe2QYD9G9fH+0v8FrTF9eSwLWe9uz31hXQ1dC2Eh5rQ/FV7rK40hwYVijjt8J3tvB1uhwYD+JX4D3J9T8NsOTU2g0XQE+HDsuCyGgrT9rdrsLenwhX5XuhNpg5r/9/6/gxtDSOJ1KtHb6bbORn2Gh/2mXZDmR730Q1ykCDVfWWSF4ovx3LfgFxk7VHGOTq9C4mza9zap0mcUt7EVi11DG+tubbxluxP188sCv5u1od+s/pLJnllmarU3mN+2GOVBHM+WsC7iJriSjLfvdYx5FQ0QIlVIVYs4bCjVsBDw6SU6uMbYvgfgrrGhV+8DIxdkQFDFNrR7j7hkdpzsdhn6p1ZAkTmGezhUdnoKzE5/u2xi4PoCYYTub5PFbr1XQ+8ZNL9y8/Yc031+3m9h1f8s97V6JclmR92+khv5Fv+HfO4t86i2cWXOsQ8PoDpuoeglLzCxFoT//mMK60wLaZITu4aVafghZ9bXncxCPfm9La2+4Kr4CmDra+6xz1u8yWDUswGqT6fEwPLJJcljhGBXlGuTnrlCU70gzdVwX5z49/hOTDVYNt1QZT2qJ9KJWKJKBSIga/dFpv+u/0dvjZNSx+2A==
  template:
    metadata:
      creationTimestamp: null
      name: storage-configuration
      namespace: minio
    type: Opaque
