---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: storage-user
  namespace: minio
spec:
  encryptedData:
    CONSOLE_ACCESS_KEY: AgAwZQk68VCpNtGIdkoMT919cgXGZIW8Db0dRFGCt4EcmwYMvDPGgYG8OM8i43XgYLqT7PQV7N9OpmZjpxDEGkNXAqazw/ItmStONqyIdX+Hf67srUCVk0B3jPjQ5ld/0AFn18dseeCP9uUxcp0R50FaWF13CEcDbCLmHag8ByfSYFg2rPEYt4Gwgse50SKoeXZg8Nh1oC8vwQ0MpcAyvcY2ZBjoT3zUKQAMOQFcdzRWALsJCQlCuT3MgpN1F73TgRnlnykh8+qudPpurzT0k/MU73z1tjqY60tSwJmxUwJNnXbOQZBghVPOmD8d3t3Mov5zzK4H4zTLXzji07kkNYANOo5/SZGi7R0WuNI7i5Mq9+6zvZc6yLU97oc05fT8x/pBfdkJbgFj9y3jlvNEiA4ZCFhve5iDCr8lSeaS/d2oJ1uO3ukEEHF0r+UNgyCbVL1P82gzXvHyVFXdO0tpE3rzuL5jIrKT7pM9CBVuLq4KIDd0coE6ANTNGw2f0csIAb9NbsIKOl2n+r/Iis6wnvyDnwhHIoqsyUEaTdD498UKp1UHddTZMruauya7frO+cvtMjHPtTsHWdbB9T/FJ7NzCTdlU3gVZIXBq87yDj1IreSk8s9F+2t8OnNlXFY0XoX48V7ssAWjQF7/ALWwNE4dhhRfv5U08Ux5YEKDWsnWQ/peiYBvCRQw6Cp8IrAU3q2OFzKhXLJob
    CONSOLE_SECRET_KEY: AgB9GUA+B6wrkXgxpUHRZJgGJ7ejF0ThW+1+OVnzsRksGaEW8eFySblVN6POd+JGm0dfJMmnD+8FXdfRFHFl2t3BI7UKKC9x9cBeOHM+KbNmhSwAoEmRRmQX6iwuhDUVzBqP3QOhdmho2B9wvC38CxMORZkFBcItNhgrZncBSDIfdsb5Dui1UD65gqUgzfed0tmIWqZhUybLisjdsW5Lv7JyIfsmZjiiQbmb4ZhxCJeO8LKPV6iJLJAWfgUqD1bdI0Yg0pCcRWgq858mnj/3zIIRVufPBTvqZsC2NnWaAUHvot43uoQuRs+ot7qKNGejbf1FZfp2NKDX+aHwySnr7lnRY24cDeHKZdkq5IDsMRWoT04O6/vB7zAunpSGxb6RXQPdNxCR+Wex3nUsMFA9v9O0Y224vFTurlajam067dptlBJG+pb6TPox2qrCvDMmmBlkdiuUonHi3kfxSd8GzwB6VI9nOSeM/STUC+GMw+O7hPKeq8euALzV4LO9DgcMAhbmcj4DSO1bZY/InzsW7rKcuAADjN3xM59Op5tW9Xk9p5g0EQuusAmE6I8hsDNKG+OEpeVYAWPqPER5r48L+4jtdzdKFHPIYf7yYUxpTMLjOltZRFettmjNWodS9Ir+xZDgSV0tb+JnQZ08lVBtJccjeX/xQfwd6j7SyX+5GR6YbnoXrHAFT3ZSwsYYfNRQCsukB04AZpCfdArW
  template:
    metadata:
      creationTimestamp: null
      name: storage-user
      namespace: minio
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: storage-configuration
  namespace: minio
spec:
  encryptedData:
    config.env: AgDAtclY1ihIzZILylGkoEglLvQaqaRt5u1knZoJW/SUNFYBeh1qirjKwwhVF7yjLUVmV+5VlbddPVliclIW0i8Q/hijwSImY9mAlT8WY586tuH2YZy4Y6/eM+5Ak8XBEiR9xmMmeUKPC7PgmDxvk0Q8gtNvVKA8KonmNzX3cYxJoM6S5NwdKAUOT7xHhgYK3VlTaICpN9dE+1zI1BxVKduLtSGCH9f0shE3GxC6h9sYVCWuQzj18YwW1npHVOt3b05QZ1r+eJie8QeqRsZ4dk2+ptqvWlyJdaa3MDmxxAkZCwm4JdV3HiEndzJ6ZMfI2ct2qK8UbFNeKW9WNs6zlHdXst/amCvIsErUK8y0oiXBnBfeNn32iy+/SoZpCbZVFfuNaGGVQTXcP5lB7xho6g2UUU+phMZm/256uUiB5g7SlQcTb0Ll33adp1G+i12mQG1pKBpBB813SaKUYD6BHycLoqgsBLTs3LrdYIpCKOcOEwvHpo4E9oRv0LXGHiU6FMyheaNe03K8Zg6RbbJksw9cg8kIBBfIBX0OST1FOQ7b5LJ+du4IU2FMt0ygQyvrOxOQVJHkKUSxVQm64LlzR6H5Wu2jqFAY7p/UHD3YGf87jynfCvQWKY0pggawG1XaeKgQn3rO40mUg1Ftx3BlTRal8UaiWIIJJrM/uF6+Jon9jB5G8BcfDX5LJgeusJmYM8Kzozk1KS5QuFPckdlqrk+t8Hh9opWl5+pqArVR5HswXhRXfeKEJuIOfz547T2BMo9Ws/6OHBd9ZdInpgc4o7ZrVBlmhcnQxQHOjBypb8tFFwWpUBuoTJgSlOwAhGeXhlYq2U6cNcG0E+IQNQsGLV/YEraagPV35WNOvytbjP5cTpQ1DefQazanNg==
  template:
    metadata:
      creationTimestamp: null
      name: storage-configuration
      namespace: minio
    type: Opaque
