---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: storage-user
  namespace: minio
spec:
  encryptedData:
    CONSOLE_ACCESS_KEY: AgBYDXwiZ4o4rmrFK7+pLYjOrqh4cH+LMtAnGwcobxJ7rkKwll6WSvvOdTae91PAjm49pJnMCGct9WIdfv93flJmuTe3hUCPqZCwXASsAOS/utkyOcHB9C22PYqqMCq0BC0RmXQ4sBF6+ub1tcK1qLKd/0Va1ITGmV3pa+2uwY3aWB+5wVThsKOZlazBrLpxqCt4rlYg87dnT1YT36M5NQr2EGX6IJZMm+L7fTiU3pFE8fDuWh3qyFwQucxNpibQwV7fO9B/PrxIQGwvj/EgnTpJyFh7pSrtlSjp6ctoqa4RDslxx7KWIljIL6SEnwVpjDDUJhf7DE5r24aAH9xoRFlD8N2a07/XLb8sz4DL9GMvqhrY3iFkVM8pQR0bqOHwN4vbkiVaxT+phswT7YD0gs3ELD+6ZDyatXDZnSrfUUiDfMFU/qQkXwLYJ5hzPzBY1Z4icWjANdmTYk5z2r8v0QV8pFWaaaK/3/ODl/ZFNOrVyGar0qO/1PPBAwfiJ+SOobdcetys8Dld264r8fqcsNVwUej+fJacuxYT4CoDK+axH8iDNVas6Wv0DCMI9+MwAg8zZYPhvjpe9qfmknWyK84rnALEKwX2pz4ZMCRuOYgo0dhUqNUvvG7SBsTYQvp61DnXbnjM3PVrcbRehq6cyXGIRBbLRNnQZ/AsByjl2P3Nnv2bOGvW/oxZirOtZnDkyyb3NdKALzGZ
    CONSOLE_SECRET_KEY: AgBmGKVsD+1pcqedLtFdrVv83jztDKwc+LrtKf2kJeRsY66t+bMyNuHL1kbxw0WlqFdz+JqAAC/RwCyzPvfOIuLvGWtif+BnR95XA3MZ9MxDKSmpTQX1fKKDrCT153jyqjdaS53CcOpbjAiNWhF54OckxnBZXOvU3Y/7FrhZWDsUPdL4GtvQnpvz+c6N2fI9K3JGoLiDojpqGIoBdoEcoAzACfkYEnfEtK4bxV6/8PU6qrpf758S2iEvuaSDW8T5lzt/HLLyDoHaanznH3sgVo0i4T+/K2eGLSfmfIhkq5C6mZe69zgHFaFA9WaF1Df5c+T+06DcAYPw1l0t7QhSU3/ApDWOFRXnVKw568tiapPk9dO77Up2O77DYYIvxFJml/EybH3d5mqgzuW7o2oUscH3aFbRZXdINuNOm1iks+DTBlwEJrtGp6maGN7o6re4d1tdyNBer2d5C3ha621q8hp6G6qq1Ly1MmQd57MY//2pJcg530n0MYvasiuieaIdZVft8DnUKOYkj1PV5j0+yPSs+PTZy+AtGvg237MbnuvUG6rrlzobLO/AVCfiDn1NFv/Fj4g0CGH5xCGQQHkEBj8rDA/xY35+sw8ASPn9unx86s7A4PTb9UZdKNXCt4MI7G1JzDLpjoRD/QKlFtlIsoR06mCT2900k7IYugK3k9izG50TI6lbJ1ILKNS6lxXMH61+wg2gJqbvFLy7
  template:
    metadata:
      creationTimestamp: null
      name: storage-user
      namespace: minio
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: storage-configuration
  namespace: minio
spec:
  encryptedData:
    config.env: AgDMvdIa+rhj7SamFWiyjuCCmLJbv8HId4pipJDhGp191ZxYcIpl5mL1EzS3CFNgWL9A19q6fATKD8cBkj+sqlvlQz9sbQaVpGViFkr9izjHjelQV60k/B3IMf4Y6zKXyIZM+IOr9TXdqXl8pl/2qUMOwpDSuazgxB8RqQzUwj2HrofyfAEHM8gZDCk7WAJ+Wqsk8gyRfAow65k47R4L9WDtaH5e/yIZeeOl68WPuuRZsQB4cbq74X3/3TJeS0tvyj8eCQP38heKkOCTTng20ERwLQ0ySih6Hqz3/b0FT6a58U7+8upgd6hCqw7IWc6rDNj5OwI7801JkeBiP1VpGzMBFIWKqyPakeksbVyg4dkjLlFSJzkTEbubt49hKOdmAJqyLo8WOkNa40zV2Q6/z8J3a9ui/+fxU3CDOK2m8eLazmdpG/R4PGQD2+1lZtT2eNNcND66AS3XtcBiUxhEgeuMX4mmulsKv7cJAjZovQRdr03koGvCDM0XwcZ5U22v/wzTR7Epbw4B2XsGY0BVnSk/WAYNpapLs0I05Oqo6XQhPjGepd04KTVpFfE/32g3fPm767Vo2IBbtvY682UeFiddnj88+GzILbMK4xl4dOAzO/rLP5XRoewQLqxJDYEwK0idj/xRCbbj2K85pGkbE0RQKqTFljBdotOxNYIkEoQpHZT4KtJDCHlNTIrC9YytaJM5Q3U0zAfY8FoSO6dLgpSiTUoTT/eF6QXEFOGBS5OM/im8awV/KXiTR2qntUK0TqZLRrz3Nq5vnu7cPzX1KguNpbT12yx0sEmnrzcXd3kIDtKyUCNjOt/73tyHQgGLqITA+0GTFR6kaEQX5sYL1BHvkx2Mx7yKCBXW3sy3UXjCWH9nBakaJlFNJg==
  template:
    metadata:
      creationTimestamp: null
      name: storage-configuration
      namespace: minio
    type: Opaque
