apiVersion: minio.min.io/v2
kind: Tenant 
metadata:
  name: s3 
  namespace: minio
spec:
  configuration:
    name: storage-configuration
  users:
  - name: storage-user
  pools:
  - servers: 3
    name: pool-0
    volumesPerServer: 2
    reclaimStorage: true
    volumeClaimTemplate:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata: { }
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 250Gi
        storageClassName: local-storage
      status: { }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: s3-console
  namespace: minio
  labels:
    name: s3-console
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: s3-console.storage.prossertech.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: s3-console
            port: 
              number: 9443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: s3
  namespace: minio
  labels:
    name: s3
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: s3.storage.prossertech.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: minio
            port: 
              number: 9000